name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the Docker image for back
        run: docker build ./back --file ./back/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/back-image:latest
      - name: Push the Docker image for back
        run: docker push ${{ secrets.DOCKER_USERNAME }}/back-image:latest

  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the Docker image for front
        run: docker build ./front --file ./front/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/front-image:latest
      - name: Push the Docker image for front
        run: docker push ${{ secrets.DOCKER_USERNAME }}/front-image:latest
