name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image for back
        run: docker build ./back --file ./back/Dockerfile --tag back-image:$(date +%s)

  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image for front
        run: docker build ./front --file ./front/Dockerfile --tag front-image:$(date +%s)
